### ISSUE TITLE
Issues with Map.py

### ISSUE THREAD

**Issue by tseemann** [Malfoy/BGREAT#2]
1.  Name too general
2.  `subprocess.call(['./BGREAT',k,readFile,unitigFile,'2','1'])` but binary is called "bgreat" and you can assume it will be in the PATH when packaged
3. `subprocess.call(['./getBigUnitig',unitigFile,'big.fa',readsize])` but binary is called "getLargeUnitigs" and in PATH when packaged

**Comment by Malfoy** [comment]
Thank you for this remark ! I modified it. The python script is just here to be a workflow starting example.
